### ISSUE TITLE
GoXLR.Plugin.exe high cpu usage

### ISSUE THREAD

**Issue by BndlfLeGlnd** [oddbear/GoXLR-TouchPortal-Plugin#18]
Hi! :)
After exiting Touch Portal App, the GoXLR.Plugin.exe burns cpu usage (around 16~20%) until shutdown manually in Task Manager.

Thanks for your help !

**Comment by oddbear** [comment]
Hi.
That is interesting, what version of the plugin and TouchPortal are you using?

**Comment by BndlfLeGlnd** [comment]
Touch Portal v2.3.008 (latest)
Plugin v0.5

(Screenshot of Task Manager after closing Touch Portal)
![Capture d’écran 2021-04-23 131121](https://user-images.githubusercontent.com/83049797/115863210-70f10e00-a435-11eb-9b35-405c2b095726.jpg)

**Comment by oddbear** [comment]
I think this is because of one of the things that changed in TouchPortal 2.3. I get the same behaviour at my computer with v0.5 (8% CPU).

I am working on an update in a different branch, and one of the fixes is this one. Here is the latest build from that branch: https://drive.google.com/file/d/1OD2bcV7IbNCkX5ETmGFcDsVAaJL6IDSm/view?usp=sharing

Please do this steps:
1. Download tpp file from link.
2. Uninstall plugin from TouchPortal, and close it from task manager if still running.
3. Install from TouchPortal... (might be a good idea to restart TouchPortal after installing a plugin)
4. Close GoXLR App
5. Start GoXLR App

I will try to release this (with a minor update) as 0.6 during the weekend.

And thanks for reporting, btw. Feedback is appreciated.

**Comment by BndlfLeGlnd** [comment]
thank you very much for your quick answer, this is a great tool!
That did the trick, no more plugin in the background.

**Comment by oddbear** [comment]
Released as v0.6
